# GeoSight is UNICEF's geospatial web-based business intelligence platform.
#
# Contact : geosight-no-reply@unicef.org
#
# .. note:: This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
# __author__ = 'irwan@kartoza.com'
# __date__ = '13/06/2023'
# __copyright__ = ('Copyright 2023, Unicef')

name: ðŸ“– Documentation
on:
  push:
    branches:
      - main
      - docs
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - ".github/workflows/BuildMKDocsAndPublishToGithubPages.yml"
      - "docs/**.md"
      - "docs/**.py"
      - "docs/assets/**"
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main from github
        uses: actions/checkout@v1
      - name: Create Mkdocs Config ðŸš€
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh
      - name: Deploy docs to github pages
        # This is where we get the material theme from
        uses: timlinux/mkdocs-deploy-gh-pages@master
        # Wrong
        #uses: timlinux/QGISAnimationWorkbench@main
        env:
          # Read this carefully:
          # https://github.com/marketplace/actions/deploy-mkdocs#building-with-github_token
          # The token is automatically generated by the GH Action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          REQUIREMENTS: docs/requirements.txt